services:
  db:
    image: postgres
    restart: always
    container_name: informationretrievalpostgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: informationretrievaldb
